version: "3.9"

services:
  job-normalizer:
    build:
      context: ./pipeline/src
      dockerfile: Dockerfile
    container_name: job_normalizer
    env_file:
      - ./pipeline/src/.env
    volumes:
      - ./pipeline/src/data:/app/data
    networks:
      - jm_network
    command: >
      python3 normalizer.py
    
networks:
  jm_network:
    name: jm_network
