# models/sources.yml
version: 2

sources:
  - name: dim_tables
    database: PFR
    schema: SILVER
    tables:
      - name: DIM_LIEU
        identifier: DIM_LIEU
        description: "Table des dimensions géographiques (code postal, ville…)"
      - name: DIM_CONTRAT
        identifier: DIM_CONTRAT
        description: "Table des dimensions des contrats"
      - name: DIM_ENTREPRISE
        identifier: DIM_ENTREPRISE
        description: "Table des dimensions des entreprises"

  - name: gold_tables
    database: PFR
    schema: GOLD
    tables:
      - name: FAIT_OFFRE
        identifier: FAIT_OFFRE
        description: "Table des faits à implémenter"

  - name: RAW
    database: PFR
    schema: RAW
    tables:
      - name: RAW_OFFRE
        identifier: RAW_OFFRE
        description: "Table d'analyses brutes des offres"
      - name: RAW_OFFRE_BIS
        identifier: RAW_OFFRE_BIS
        description: "Table d'analyses brutes des offres plus petite "
