# models/sources.yml
version: 2

sources:
  - name: dim_tables
    database: PFR
    schema: SILVER
    tables:
      - name: dim_lieu
        identifier: DIM_LIEU
        description: "Table des dimensions géographiques (code postal, ville…)"
      - name: dim_contrat
        identifier: DIM_CONTRAT
        description: "Table des dimensions des contrats"
      - name: dim_entreprise
        identifier: dim_entreprise
        description: "Table des dimensions des entreprises"
    schema: GOLD
    tables:
      - name: FAIT_OFFRE
        identifier: FAIT_OFFRE
        description: "Table des faits à implémenter"



  - name: raw
    database: PFR
    schema: RAW
    tables:
      - name: RAW_OFFRE
        identifier: RAW_OFFRE
        description: "Table d’analyses brutes des offres"
