services:
  backend:
    image: jm-backend
    container_name: jm-backend
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - jm_network
    ports:
      - "8082:8000"
    env_file:
      - .env
    volumes:
      - ./:/usr/src/backend
  # redis:
  #   container_name: redis
  #   image: redis:7.2.0
  #   networks:
  #     - jm_network
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - ./data:/data

networks:
  jm_network:
    name: jm_network
