services:
  jm-etl-snowflake:
    image: jm-etl-snowflake
    container_name: jm-etl-snowflake
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - jm_network
    env_file:
      - .env
    volumes:
      - ./snowflake:/usr/src/snowflake
      - ./data:/usr/src/data

networks:
  jm_network:
    name: jm_network
